
import React from 'react';

export const Disclaimer: React.FC = () => {
  return (
    <footer className="mt-12 text-center text-xs text-gray-500 px-4">
      <p>
        <strong>Disclaimer:</strong> This tool provides informational guidance and is not a substitute for professional medical advice.
        The information is generated by an AI and may not be fully accurate or complete.
        Always consult with a healthcare provider for any health-related concerns during pregnancy. 💛
      </p>
    </footer>
  );
};
